on:
  push:
    branches:
      - main

name: Create thena release from a tag
jobs:
  build:
    name: Create Release
    if: "!startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.REPO_TOKEN }}

    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        gpg-private-key: ${{ secrets.HDES_GPG_KEY }}
        gpg-passphrase: GPG_KEY_SEC
        server-id: oss.sonatype.org
        server-username: OSSRH_USER
        server-password: OSSRH_PASS
    
    - name: Maven release
      run: ./thena-build-parent/release.sh
      env:
        BOT_NAME: olev.mutso
        BOT_EMAIL: olev.mutso@resys.io
        GPG_KEY_SEC: ${{ secrets.GPG_KEY_SEC }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}

        
