on:
  push:
    branches:
      - main

name: Create thena release from a tag
jobs:
  build:
    name: Create Release
    if: "!startsWith(github.event.head_commit.message, 'release')"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: main
        token: ${{ secrets.REPO_TOKEN }}

    - uses: actions/setup-java@v4
      with:
        java-version: '11'
    
    - name: Maven release
      run: ./thena-build-parent/release.sh
      env:
        CI: false
        BOT_NAME: olev.mutso
        BOT_EMAIL: olev.mutso@resys.io
        GITHUB_SHA: ${GITHUB_SHA}
        GITHUB_REF: ${GITHUB_REF}
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GPG_KEY: ${{ secrets.HDES_GPG_KEY }}
        GPG_KEY_SEC:  ${{ secrets.GPG_KEY_SEC }}
        OSSRH_PASS: ${{ secrets.OSSRH_PASS }}
        OSSRH_USER: ${{ secrets.OSSRH_USER }}
        
        
